name: CI/CD - Face Swap Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 132690414014
  ECR_BACKEND: ai-face-swap-backend
  ECR_FRONTEND: ai-face-swap-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        run: |
          docker build -t backend ./app/backend
          docker tag backend:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND:latest

      - name: Build frontend image
        run: |
          docker build -t frontend ./app/frontend
          docker tag frontend:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND:latest

      - name: Deploy via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=tag:DeployTarget,Values=face-swap-dev" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="cd /opt/ai-face-swap/app && docker compose pull && docker compose up -d --remove-orphans" \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"
